/**
 * English workspace copy lives here so views and state helpers do not become
 * translation surfaces. Protocol tokens, CSS classes, and persisted values do
 * not belong in this catalog.
 */
export const workspaceText = {
  title: 'Hermes workspace',
  hermes: 'Hermes',
  you: 'You',
  system: 'System',
  tool: 'Tool',
  newChat: 'New chat',
  search: 'Search',
  allProfiles: 'All profiles',
  pinned: 'Pinned',
  recent: 'Recent',
  archived: 'Archived chats',
  schedules: 'Schedules',
  noChats: 'No chats yet',
  noArchived: 'No archived chats',
  noSchedules: 'No schedules',
  noSearchResults: 'No matching messages',
  selectChat: 'Select a chat or start a new one',
  disconnected: 'Disconnected. Loaded content stays visible; sending and changes are disabled.',
  incompatible: 'This Hermes instance does not provide the core workspace API.',
  reconnect: 'Reconnect',
  reconnectToSend: 'Reconnect to send',
  composerChangedWhilePreparing: 'Composer changed while Hermes was preparing; send again',
  restoreBeforeSending: 'Restore this chat before sending messages',
  copyDetails: 'Copy error details',
  loadEarlier: 'Load earlier messages',
  messagePlaceholder: 'Message Hermes…',
  queue: 'Queued prompts',
  addSchedule: 'New schedule',
  save: 'Save',
  cancel: 'Cancel',
  notAvailable: '—',

  branchedChat: 'Branched chat',
  untitledChat: 'Untitled chat',
  copy: 'Copy',
  retry: 'Retry',
  editAndResubmit: 'Edit and resubmit',
  branchFromHere: 'Branch from here',
  undoLatestExchange: 'Undo latest exchange',
  latestExchangeOnly: 'Hermes Gateway can undo only the latest exchange',
  tasks: 'Tasks',
  complete: 'complete',
  artifacts: 'Artifacts',
  openGatewayFile: 'Download from Hermes gateway',
  reconnectToOpenGatewayFile: 'Reconnect to open gateway files',
  gatewayFolderUnavailable: 'Folder references cannot be downloaded as files',
  gatewayFilePreviewUnavailable: 'Gateway image preview unavailable',
  gatewayFileUnsafe: 'Hermes returned unsafe gateway image data',
  openGatewayFileFailed: (reason: unknown) => `Could not download gateway file: ${String(reason)}`,
  tokenUsage: 'Token usage',
  session: 'Session',
  message: 'Message',
  input: 'input',
  output: 'output',
  total: 'total',
  context: 'context',
  reasoning: 'Reasoning',
  tokens: 'tokens',
  historicalRequest: 'Historical request — respond from the client that owns the turn.',
  enterSecret: 'Enter secret',
  typeResponse: 'Type a response',
  send: 'Send',

  scheduleFailed: 'Hermes schedule failed',
  scheduleCompleted: 'Hermes schedule completed',
  hermesFinished: 'Hermes finished',
  chatCompleted: 'Chat completed',
  hermesNeedsApproval: 'Hermes needs approval',
  hermesHasQuestion: 'Hermes has a question',
  restoreDraftsAndQueues: (reason: unknown) => `Could not restore drafts and queues: ${String(reason)}`,
  restoreQueuedChats: (failures: string[]) => `Could not restore queued chats: ${failures.join('; ')}`,
  missingPromptForResponse: 'Could not find the prompt for this response',
  editMessage: 'Edit message',
  emptySlashCommand: 'Empty slash command',
  commandOutsideSurface: (name: string) => `/${name} is outside the Ask Hermes workspace command surface`,
  sessionTitleSet: (title: string) => `Session title set: ${title}`,
  resumeUsage: 'Usage: /resume <session id or title>',
  noMatchingSession: (query: string) => `No session matching “${query}”`,
  chooseModelInControls: 'Use Chat controls to choose a model and provider.',
  unknownModel: (model: string) => `Unknown model “${model}”`,
  modelSetForNextTurn: (label: string, provider?: string) => `Model set for the next turn: ${label}${provider ? ` · ${provider}` : ''}`,
  commandQueued: 'Command prompt queued for this chat.',
  warning: (warning: string) => `Warning: ${warning}`,
  commandNoOutput: (name: string) => `/${name}: no output`,
  steerUsage: 'Usage: /steer <prompt>',
  steerAttachmentsUnsupported: 'Steering does not support attachments',
  steeringRejected: 'Hermes did not accept the steering message',
  steered: (prompt: string) => `Steered: ${prompt}`,
  slashAttachmentsUnsupported: 'Slash commands do not support attachments',
  uploadLimitExceeded: (name: string) => `${name} exceeds the 16 MB upload limit`,
  handoffUploadFailed: 'Could not transfer all prompt attachments to the workspace',
  handoffStaleInstance: 'Prompt handoff belongs to a different Hermes instance generation',
  handoffSessionOpenFailed: 'Workspace could not open the handoff session',
  handoffProfileUnavailable: 'Workspace could not resolve a profile for the prompt handoff',
  handoffSuperseded: 'Prompt handoff was superseded before the workspace could apply it',
  urlToInclude: 'URL to include',
  httpUrlsOnly: 'Only HTTP and HTTPS URLs are supported',
  invalidUrl: (reason: unknown) => `Invalid URL: ${String(reason)}`,
  noSpeechDetected: 'No speech was detected',
  voiceInputError: (reason: unknown) => `Voice input: ${String(reason)}`,
  voiceRecordingFailed: 'Voice recording failed',
  instanceNoLongerConfigured: (instanceId: string) => `Hermes instance ${instanceId} is no longer configured`,

  hideWorkspace: 'Hide workspace',
  profile: 'Profile',
  workspace: 'Workspace',
  loading: 'Loading…',
  loadMoreChats: (loaded: number, total?: number) => `Load more chats${total ? ` (${loaded}/${total})` : ''}`,
  showSidebar: 'Show sidebar',
  hideSidebar: 'Hide sidebar',
  refresh: 'Refresh',
  connectingToHermes: 'Connecting to Hermes…',
  searchChats: 'Search chats',
  searchDescription: 'Gateway-backed search across titles and message content.',
  searchMessages: 'Search messages',
  searching: 'Searching…',
  filters: 'Filters',
  active: 'Active',
  archivedFilter: 'Archived',
  source: 'Source',
  any: 'Any',
  workspaceSource: 'Workspace',
  desktopSource: 'Desktop',
  cliSource: 'CLI',
  scheduleSource: 'Schedule',
  messagingSource: 'Messaging',
  from: 'From',
  to: 'To',
  partialSearchResults: 'Hermes Gateway returned partial results. Refine the search query for complete coverage.',
  enterSearchQuery: 'Enter a search query.',
  loadMoreResults: 'Load more results',

  editSchedule: 'Edit schedule',
  name: 'Name',
  prompt: 'Prompt',
  cronExpression: 'Cron expression',
  cronPlaceholder: '0 9 * * 1-5',
  model: 'Model',
  provider: 'Provider',
  hermesDefault: 'Hermes default',
  agentJobsFor: (profile: string) => `Agent jobs for ${profile}.`,
  allProfilesLower: 'all profiles',
  searchSchedules: 'Search schedules',
  next: 'Next',
  resume: 'Resume',
  pause: 'Pause',
  runNow: 'Run now',
  edit: 'Edit',
  cron: 'Cron',
  nextRun: 'Next run',
  lastRun: 'Last run',
  runHistory: 'Run history',
  noRuns: 'No runs yet.',
  finishedAt: (time: string) => `Finished ${time}`,
  inProgress: 'In progress',
  loadMore: 'Load more',
  deleteScheduleConfirmation: (name: string) => `Permanently delete schedule “${name}”?`,

  stop: 'Stop',
  chatOptions: 'Chat options',
  chatTitle: 'Chat title',
  rename: 'Rename',
  pin: 'Pin',
  unpin: 'Unpin',
  branch: 'Branch',
  archive: 'Archive',
  restore: 'Restore',
  deletePermanently: 'Delete permanently',
  deleteChatConfirmation: (title: string) => `Permanently delete “${title}”?`,
  loadingMessages: 'Loading messages…',
  agentActivity: 'Agent activity',
  retryQueuedPrompts: 'Retry queued prompts',
  moveUp: 'Move up',
  moveDown: 'Move down',
  remove: 'Remove',
  addContext: 'Add context',
  attachFiles: 'Attach files',
  attachFolder: 'Attach folder',
  addUrlReference: 'Add URL reference',
  captureScreen: 'Capture screen',
  stopVoiceInput: 'Stop voice input (Ctrl+Shift+D)',
  transcribingVoiceInput: 'Transcribing voice input…',
  voiceInput: 'Voice input (Ctrl+Shift+D)',
  chatControls: 'Chat controls',
  reasoningSetting: 'Reasoning',
  default: 'Default',
  fastMode: 'Fast mode',
  personality: 'Personality',
  approvals: 'Approvals',
  yolo: 'YOLO',
  removeFailedAttachments: 'Remove failed attachments before sending',
  retryFailedAttachments: 'Retry failed attachments and send',
  waitForAttachments: 'Wait for attachments to finish uploading',
  addToQueue: 'Add to queue',
  quitConfirmation: 'Active turns or queued prompts exist. Quit anyway?',
  workspaceTurnReconnecting: 'Workspace turn is active, but its profile is still reconnecting. Try again shortly.',
  waitBeforeInstanceSwitch: 'Wait for active turns and queued prompts before switching Hermes instances',
  openWorkspace: 'Open workspace',
  openWorkspaceQueueEdit: 'Open workspace to edit queued prompts',
  queuedCount: (count: number) => `${count} queued`,
  queueForHermes: 'Queue for Hermes',
  trayLinks: 'Tray links',
  workspaceOnly: 'Workspace only',
  hermesDesktopOnly: 'Hermes Desktop only',
  showBoth: 'Show both',
  notifications: 'Notifications',
  turnCompleted: 'Turn completed',
  interactionRequired: 'Approval or clarification required',
  scheduleFailedSetting: 'Schedule failed',
  scheduleCompletedSetting: 'Schedule completed',
  automaticHermes: 'Automatic Hermes',
  existingHermes: 'Existing Hermes',
  newHermesInstance: 'New Hermes instance',
  hermesInstance: 'Hermes instance',
  existingHermesInstance: 'Existing Hermes instance',
  connection: 'Connection',
  addInstance: 'Add instance',
  address: 'Address',
  port: 'Port',
  sessionTokenOptional: 'Session token (optional)',
  localDerpAgent: 'Local derp-agent',
  invalidHermesHost: 'Enter a valid Hermes hostname or IP address',
  invalidHermesPort: 'Hermes port must be between 1 and 65535',

  capabilityMissing: (name: string) => `Hermes did not report ${name} support`,
  stopBeforeLifecycleMutation: 'Stop the active turn before archiving or deleting this chat',
  removeQueueBeforeLifecycleMutation: 'Remove queued prompts before archiving or deleting this chat',
  attachmentOnlyPrompt: 'Please review the attached files.',
  unavailableChat: (sessionId: string) => `Unavailable chat (${sessionId})`,
} as const
